<?php

return [
    'ai_workspace_manual' => [
        'name' => 'GEOFlow 后台功能与操作指南（AI 工作台专用）',
        'description' => 'GEOFlow AI 工作台用于解释后台功能、流程、原理、故障恢复和可信站内入口的系统知识。',
        'official_version' => '2026.08.28.1',
        'authoritative_locale' => 'zh_CN',
        'content_file' => 'geoflow-admin-guide.zh_CN.md',
        'content_hash' => '785808eb8003af5f00b36d6af7c71782a73fbb1b0f74c02539b8eb5ff116bce6',
        'minimum_han_characters' => 10_000,
        'required_sections' => [
            '## 一、系统总览与工作方法',
            '## 二、AI 工作台',
            '## 三、数据中心与效果分析',
            '## 四、任务管理与内容生产',
            '## 五、文章管理与质量控制',
            '## 六、内容资产',
            '## 七、企业知识库与 URL 导入',
            '## 八、内容分发与托管站点',
            '## 九、人工发布与浏览器运营助手',
            '## 十、网站、主题与线索',
            '## 十一、AI 配置、模型与提示词',
            '## 十二、用户、权限、安全与审计',
            '## 十三、系统更新、部署与运行维护',
            '## 十四、API、CLI 与扩展能力',
            '## 十五、通用排查方法与回答原则',
        ],
        'required_route_names' => [
            'admin.account.browser-clients.index',
            'admin.account.show',
            'admin.admin-activity-logs',
            'admin.admin-users.index',
            'admin.ai-models.index',
            'admin.ai-prompts',
            'admin.ai-workspace',
            'admin.ai.configurator',
            'admin.analytics',
            'admin.analytics.ai-visibility',
            'admin.analytics.content',
            'admin.articles.create',
            'admin.articles.index',
            'admin.dashboard',
            'admin.distribution.hosted-sites.index',
            'admin.distribution.index',
            'admin.enterprise-knowledge.index',
            'admin.knowledge-bases.index',
            'admin.lead-forms.index',
            'admin.leads.index',
            'admin.manual-publications.index',
            'admin.materials.index',
            'admin.security-settings.index',
            'admin.site-settings.index',
            'admin.system-updates.index',
            'admin.tasks.create',
            'admin.tasks.index',
            'admin.title-libraries.index',
            'admin.url-import',
        ],
    ],
];
